# restart the server by running 'bundle exec jekyll serve' if this file has been edited

# use in templates via {{ site.myvariable }}.
title: brandon dao
email: elmobey@gmail.com
description: >-
  getting motivated to do things / reflections on experiences / other interests
url: https://daosyn.info
github_url: https://github.com/daosyn

# build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
