#!/bin/bash

red='\e[31m'
nocolor='\e[00m'

cat << "EOF"
environment installation script

created by and designed personally for:

       __                                              
      /\ \                                             
      \_\ \     __      ___     ____  __  __    ___    
      /'_` \  /'__`\   / __`\  /',__\/\ \/\ \ /' _ `\  
     /\ \L\ \/\ \L\.\_/\ \L\ \/\__, `\ \ \_\ \/\ \/\ \ 
     \ \___,_\ \__/.\_\ \____/\/\____/\/`____ \ \_\ \_\
      \/__,_ /\/__/\/_/\/___/  \/___/  `/___/> \/_/\/_/
                                          /\___/       
                                          \/__/     

https://daosyn.info/about/

this script will:
- determine the operating system
- install packages
- set up environment-specific software
- configure gpg
- clone dotfiles and bin repositories

--------------------------------------------------
EOF

read -sp "press enter to continue, ctrl+c to quit"
echo

os=`uname -s`
echo -e "\n${red}determining operating system ($os) and installing software...${nocolor}\n"
if [ "$os" == "Linux" ]; then # Debian
    packages='chromium git golang gpg redshift vim'
    sudo apt update
    sudo apt install $packages -y
    sudo apt autoremove -y

    # TODO set up suckless
elif [ "$os" == "Darwin" ]; then # macOS
    # xcode
    xcode-select --install

    # homebrew
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew bundle --file=$HOME/.brewfile
    brew cleanup

    # use latest bash
    sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
    chsh -s /usr/local/bin/bash
elif [ "$os" == "???" ]; then # OpenBSD
    # TODO
    echo "not implemented"
else
    echo "unknown operating system! aborting"
    exit 1
fi

# TODO figure out how to set up tewi font

echo -e "\n${red}configuring gpg...${nocolor}\n"
curl https://daosyn.info/pubkey.asc | gpg --import
echo -e "trust\n5\ny\nquit\n" | gpg --command-fd 0 --edit-key daosyn@gmail.com
# TODO need to add some stuff here

echo -e "\n${red}setting up dotfiles and scripts...${nocolor}\n"
dotdir=$HOME/.dotfiles
git clone --bare https://github.com/daosyn/dotfiles.git $dotdir
git --git-dir=$dotdir/ --work-tree=$HOME checkout -f
git --git-dir=$dotdir/ --work-tree=$HOME config --local status.showUntrackedFiles no
git clone https://github.com/daosyn/bin.git $HOME/bin

echo -e "\n${red}downloading wallpapers...${nocolor}\n"
git clone https://github.com/daosyn/wallpapers.git $HOME/wallpapers

echo -e "\n${red}sourcing .bashrc...${nocolor}\n"
. $HOME/.bashrc

echo -e "\ndone!\n"
